spring.application.name=gestion-turnos
# 1. Configuración de la URL de conexión y el Driver de MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/gestion_turnos
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# 2. Credenciales de acceso a la base de datos
spring.datasource.username=root
spring.datasource.password=admin
# 3. Configuración de JPA para usar el dialecto de MariaDB
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
# 4. Configuración de Hibernate para validar el esquema de la base de datos
spring.jpa.hibernate.ddl-auto=validate
# 5. Configuración de logging para mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
// Configuración de la clave secreta para JWT (debe ser segura y de al menos 64 caracteres para cumplir con los 512 bits)
jwt.secret=un_hash_aleatorio_y_seguro_de_al_menos_64_caracteres_para_cumplir_con_los_512_bits